    $env:TF_VAR_public_ip_name                     =       'prod_public_ip'
    $env:TF_VAR_resource_group_name                =       'prod_virtual_network'
    $env:TF_VAR_pip_allocation_method              =       'Dynamic'
    $env:TF_VAR_environment                        =       'prod'
    $env:TF_VAR_location                           =       'eastus'
    $env:TF_VAR_cost_center                        =       'dji_portal'