    $env:TF_VAR_subnet_name                        =       'data'
    $env:TF_VAR_address_prefixes                   =       '10.160.3.0/24'
    $ENV:TF_VAR_service_endpoints                  =       '["Microsoft.KeyVault", "Microsoft.Storage"]' 
    $env:TF_VAR_environment                        =       'prod'
    $env:TF_VAR_location                           =       'eastus'
    $env:TF_VAR_cost_center                        =       'dji_portal'